merge: вынес логику в сторы, добавил днд, переносы компонентов в связи с обновлениями
Stormuke/react-burger pull request #3
Opened 2022-09-18 18:58 UTC by Stormuke

1. config: обновил конфиг
2. env.d.ts: добавил тип ошибки и эндпоинт
3. chore(Providers): вынес все провайдеры приложения
4. chore(burgerIngredients): удалил моки
5. chore(constants): исправил базовый урл для расширения
6. feat(apiInstance): базовый запрос
7. feat(withProviders): сгрупировал провайдеры
8. feat(Loader): окно заглушки при загрузках
9. feat(Spinner): спиннер для лоадера
10. chore(BurgerElement): вынес элемент бургера
11. chore(Card): вынес карточку ингредиента
12. feat(types): добавил новые типы, типизировал сторы
13. feat(BurgerConstructor): добавил пустое окно без ингредиентов, добавил данные из стора по заказу, перенес логику открытия попапа, добавил днд
14. chore(BurgerIngredients): перенос логики табов в стор
15. feat(App): добавил лоадер на начальную загрузку
16. squash(Cards)
     1. refactor(Cards): удалил стили связаные с карточкой
     2. feat(Cards): добавил данные из стора, изменил наполнение табов
19. feat(OrderDetails): добавил лоадер, номер заказа
20. feat(PageWithConstructor): удалил стейты, вынес пост запрос в стор
21. feat(Routing): добавил начальный запрос ингредиентов
22. feat(rootReducer): добавил рут редюсер
23. feat(OrderStore): стор заказов(экшены, селекторы, редюсеры)
24. feat(ingredientsStore): стор ингредиентов(экшены, селекторы, редюсеры)
25. feat(services): экспорт сторов для доступности по всему приложению

2022-09-18 20:12 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

### **Вы молодец! Отличная работа!** 🔥

- Декомпозиция файлов по директориям соответствует описанию;
- Сборка и запуск проекта выполняются без ошибок;
- Используются функциональные компоненты;
- Используются css-modules, что тоже очень удобно и является хорошей практикой;
- Используются typescript;
- Используются redux-toolkit на полную;

### **Но есть несколько замечаний, которые нужно исправить:**

- Не правильно считается цена булок, и их количество. Цена 1 булки должна умножиться на 2, а не на 3. и соответственно кол-во тоже будет равно 2.

- Компонент BurgerIngredients по макету и заданию, должен представлять собой список, в котором присутствуют все типы ингридиентов, а не табы. Клик по табу, должен скроллить список, до нужной категории ингридиентов.

- У некоторых компонентов задан атрибут key. Дело в том, что в этом нет необходимости, т.к. ключи имеют смысл только в контексте окружающего массива. https://reactjs.org/docs/lists-and-keys.html#extracting-components-with-keys

### **Сделает код лучше:**

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders

- В некоторых местах нарушено форматирование кода, проблемы с отступами, это затрудняет чтение кода. Об оформлении кода можно почитать здесь https://learn.javascript.ru/coding-style. Постарайтесь использовать автоматическое форматирование, это сильно экономит время. Одно из наиболее популярных дополнений для форматирования кода - Prettier (https://prettier.io/)

**_Более подробно эти и более мелкие мелкие замечания, отмечены в коде._**

2022-09-18 20:12 UTC, ArslanDev666 commented on src/components/Cards/Cards.tsx
> +          key={v4()}
**Надо исправить:** Такая генерация key, может вызвать ошибку, т.к при каждом ререндере key будет всегда новый. Каждый раз, когда изменяется ключ компонента, React будет [создавать новый экземпляр компонента, а не обновлять текущий](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key) , поэтому для повышения производительности использование uuid будет, неоптимальным.

Кроме того, если вы каким-либо образом переупорядочиваете свой список компонентов, использование индекса в качестве ключа также не будет полезным, поскольку React не сможет просто перемещаться по существующим узлам DOM, связанным с компонентами, вместо этого ему придется повторно -создать DOM-узлы для каждого элемента списка, которые, опять же, будут иметь неоптимальную производительность.

Но повторюсь, это будет проблемой только в том случае, если вы будете переупорядочивать список, поэтому в вашем случае, если вы уверены, что не будете переупорядочивать свой список каким- либо образом, вы можете безопасно использовать индекс в качестве ключа.

Однако, если вы намерены изменить порядок списка (или просто на всякий случай), я бы сгенерировал уникальные идентификаторы для ваших сущностей, если ранее не существовало уникальных идентификаторов, которые вы могли бы использовать.

Быстрый способ добавить идентификаторы — просто отобразить список и присвоить индекс каждому элементу при первом получении (или создании) списка .

```js
const myItemsWithKeys = myItems.map((item, index) => { ...item, key: uuidv4()});
```

2022-09-18 20:12 UTC, ArslanDev666 commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +        key: '1',
**Можно лучше:** Тут и далее, лучше использовать uuid.

2022-09-18 20:50 UTC, Stormuke commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +              <BurgerElement item={item} index={index} key={item.key} />
если добавить два одинаковых ингредиента,  получим ошибку одинаковых ключей, так как _id будет одинаковый

2022-09-19 05:33 UTC, ArslanDev666 commented on src/components/BurgerConstructor/BurgerConstructor.tsx
> +              <BurgerElement item={item} index={index} key={item.key} />
Действительно, тогда всё в порядке. Исправлять не нужно.

2022-09-20 07:39 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Хорошая работа. Все замечания были исправлены. Вы молодцы.

2022-09-20 07:39 UTC, ArslanDev666 commented on src/components/Cards/Cards.tsx
> +  );
**Можно лучше:** Тут лучше использовать `useMemo`, и на выходе получать, единожды, готовый результат.
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2022-09-20 07:39 UTC, ArslanDev666 commented on src/components/Cards/Cards.tsx
>          </div>
**Можно лучше**

у каждой категории ингредиентов дублируется верстка, лучше вынести отдельный компонент ingredients-category и переиспользовать его

2022-09-21 17:44 UTC, merged